spring:
  datasource:
    url: jdbc:mysql://database-1.c5sqmoige2ob.ap-south-1.rds.amazonaws.com:3306/springboot_mysql_example?autoReconnect=true&useSSL=false
    username: admin
    password: admin1234
#    url: jdbc:mysql://localhost:3306/springboot_mysql_example?autoReconnect=true&useSSL=false
#    username: root
#    password: root
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
